import './globals.css'
import Navbar from '@/components/Navbar'
import Image from 'next/image'
import background from "public/imgs/background-wallpaper.png"

export default function RootLayout({ children }) {
  return (
    <html lang="es" translate='no'>
      <head>
        <title>Alejandro Dalzotto - Portfolio</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="bg-[radial-gradient(145.05%_100%_at_50%_0%,#1D2B41_0%,#020509_57.38%,#0F1A29_88.16%)]">
        <Image src={background} alt="background" className='fixed z-[-1] top-0 left-0 w-screen h-screen opacity-20 md:hidden' />
        <Navbar />
        <div className='min-h-[calc(100%-300px)]'>
          {children}
        </div>

      </body>
    </html>
  )
}
